#!/bin/sh

source "$(git --exec-path)/git-sh-setup"

USAGE="<search>"

function _branch_grep() {
    if [[ $# == 1 ]]; then
        git branch --list --format "%(refname:short)" | grep $1
    else
        usage
    fi  
}

_branch_grep $1

